export const DEFAULT_API_BUSINESS_CODES = [
  "ok",
  "api_error",
  "invalid_argument",
  "not_found",
  "confirmation_required",
  "operation_busy",
  "operation_cancelled",
  "operation_obsolete",
  "operation_invalid_input",
  "operation_failed",
  "inspection_required",
  "inspection-required",
  "unsupported_lock_kind",
  "object_not_found",
  "lock_batch_empty",
  "lock_batch_invalid",
  "regeneration_lock_conflict",
  "inspection_stale",
  "inspection-stale",
  "inspection-token-invalid",
  "inspection-action-mismatch",
  "inspection-input-mismatch",
  "inspection-schema-mismatch",
  "grid-structure-invalid",
  "grid-preparation-invalid",
  "refinement-topology-violation",
  "refinement-invalid-structure",
  "map-cell-limit-exceeded",
  "invalid_place_reference",
  "invalid_place_kind",
  "invalid_place_id",
  "place_not_found",
  "place_removed",
  "place_anchor_invalid",
  "screen_distance_unavailable"
] as const;

export const COLLECTION_IMPORT_API_BUSINESS_CODES = [
  "ok",
  "invalid-collection-kind",
  "notes-not-importable",
  "import-unchanged",
  "invalid-measurements",
  "empty-measurements",
  "invalid-namebase-document",
  "empty-namebases",
  "invalid-military-events",
  "empty-military-events",
  "inspection-required",
  "inspection-stale",
  "inspection-token-invalid",
  "inspection-action-mismatch",
  "inspection-input-mismatch",
  "inspection-schema-mismatch",
  "confirmation_required",
  "invalid-argument",
  "invalid_argument"
] as const;

export const API_SCHEMA_VERSION = "1.0.0" as const;
export const API_DOCUMENTATION = "api-description-registry" as const;
